---
title: "CNV_SVM"
author: "Mukai Wang"
date: "July 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(e1071)
library(dplyr)
library(tictoc)
```

```{r}
gdsc = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/gdsc_screened.rds')
cnv = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/cnNEW.rds')
```


```{r}
names(cnv) <- make.names(names(cnv))
```

```{r}
get.t <- function(dat, labs){
    # split the data into effective and ineffective
    effect <- dat[labs]
    ineffect <- dat[!labs]
    
    # calculate the two sample means
    effect.bar <- mean(effect)
    ineffect.bar <- mean(ineffect)
    
    # calculate the two sample variances
    v.effect <- var(effect)
    v.ineffect <- var(ineffect)
    
    # calculate the sample sizes
    n.effect <- length(effect)
    n.ineffect <- length(ineffect)
    
    # calculate the sd
    s <- sqrt((v.effect/n.effect) + (v.ineffect/n.ineffect))
    
    # calculate the test statistic
    T <- (effect.bar - ineffect.bar)/s
    
    # calculate the degrees of freedom
    # df = ((v.effect/n.effect+v.ineffect/n.ineffect)^2)/(v.effect^2/(n.effect^2 * (n.effect-1))+v.ineffect^2/(n.ineffect^2 * (n.ineffect-1)))
    
    # compare our t value and the threshold, decide whether we should keep it or not
    return(abs(T))
}
```

```{r}
traindirect = '/home/wangmk/UM/Research/BDSI/train_drug/'
```


```{r}
code = "1062"

sigdir = '/home/wangmk/UM/Research/BDSI/Data_Results/Significant_CNV/'
filename = paste(c('significant_',code,'.rds'),collapse='')
fullname = paste(c(sigdir,filename),collapse='')
subset_id = readRDS(fullname)

accuracy = rep(0,5)
names(accuracy) = c('2','3','4','5','6')
gdsc_sub <- subset(gdsc, DRUG_ID_lib == code)[,c("CL","EFFECT")]
cnv_sub <- cnv[as.character(gdsc_sub$CL),subset_id]

filename = paste(c('train_',code,'.rds'),collapse='')
fullname = paste(c(traindirect,filename),collapse='')
cl_train = paste(readRDS(fullname))
cl_test = setdiff(rownames(cnv_sub),cl_train)

cnv_sub_train = cnv_sub[cl_train,]
cnv_sub_test = cnv_sub[cl_test,]
cnv_sub = NULL

gdsc_sub_train = tbl_df(gdsc_sub) %>% filter(CL %in% cl_train)
gdsc_sub_test = tbl_df(gdsc_sub) %>% filter(CL %in% cl_test)
```


```{r}
traindirect = '/home/wangmk/UM/Research/BDSI/train_drug/'
```

```{r}
outcome <- data.frame(Gene = colnames(cnv_sub_train))
```

```{r}
outcome$T <- apply(cnv_sub_train, 2, get.t, gdsc_sub_train$EFFECT)
```

```{r}
n_features =c(2,3,4,5,6)
costs = rep(0,5)
gammas =rep(0,5)
names(costs) = c('2','3','4','5','6')
names(gammas) = c('2','3','4','5','6')
```

```{r}
for (n_feature in n_features){
  print(n_feature)
  subset_id = outcome %>% top_n(n_feature,T) %>% select(Gene)
  subset_id = as.character(unname(t(subset_id[,1])))
  cnv_sub_train_reduced = cbind(cnv_sub_train[,subset_id],gdsc_sub_train['EFFECT'])
  cnv_sub_train_reduced$EFFECT = as.factor(cnv_sub_train_reduced$EFFECT)
  tune.out = tune ( svm , EFFECT~., data = cnv_sub_train_reduced , 
                 ranges = list ( cost = c (0.01 , 0.1 , 1 ,10 ,100),gamma=c(0.01,0.1,1,10,100) ) )
  costs[toString(n_feature)] = tune.out$best.model$cost
  gammas[toString(n_feature)] = tune.out$best.model$gamma
  for (j in 1:10){
    print(j)
    set.seed(j)
    train_id = sample(1:nrow(gdsc_sub_train),0.9*nrow(gdsc_sub_train))
    cnv_sub_traintrain_full = cbind(cnv_sub_train[train_id,subset_id],gdsc_sub_train[train_id,'EFFECT'])
    cnv_sub_traintest_full = cbind(cnv_sub_train[-train_id,subset_id],gdsc_sub_train[-train_id,'EFFECT'])
    cnv_sub_traintrain_full$EFFECT =as.factor(cnv_sub_traintrain_full$EFFECT)
    cnv_sub_traintest_full$EFFECT =as.factor(cnv_sub_traintest_full$EFFECT)
    mysvm = svm(EFFECT~.,data=cnv_sub_traintrain_full,kernel="radial",cost=tune.out$best.model$cost,gamma=tune.out$best.model$gamma,scale=FALSE)
    test_pred = predict(mysvm,cnv_sub_traintest_full)
    accuracy[toString(n_feature)] = accuracy[toString(n_feature)]+mean(test_pred==cnv_sub_traintest_full[['EFFECT']])
  }
}
```

```{r}
accuracy/10
which.max(accuracy)
tune.out$best.model$cost
tune.out$best.model$gamma
```

```{r}
subset_id = outcome %>% top_n(2,T) %>% select(Gene)#needs to be changed
subset_id = as.character(unname(t(subset_id[,1])))
```

```{r}
cnv_sub_train_reduced = cbind(cnv_sub_train[,subset_id],gdsc_sub_train['EFFECT'])
cnv_sub_train_reduced$EFFECT = as.factor(cnv_sub_train_reduced$EFFECT)
cnv_sub_test_reduced = cbind(cnv_sub_test[,subset_id],gdsc_sub_test['EFFECT'])
cnv_sub_test_reduced$EFFECT = as.factor(cnv_sub_test_reduced$EFFECT)
```

```{r}
mysvm = svm(EFFECT~.,data=cnv_sub_train_reduced,kernel="radial",cost=costs['2'],gamma=gammas['2'],scale=FALSE)# needs to be changed
```

```{r}
test_pred = predict(mysvm,cnv_sub_test_reduced)
test_pred = as.data.frame(test_pred)
```

```{r}
comp = cbind(test_pred,cnv_sub_test_reduced['EFFECT'])
```

```{r}
sum(comp$test_pred==comp$EFFECT)/nrow(comp)
```

```{r}
outdir = '/home/wangmk/UM/Research/BDSI/Data_Results/SVM/'
```

```{r}
fname = paste(c("CNV_SVM_",code,'.rds'),collapse='')
fullname = paste(c(outdir,fname),collapse='')
saveRDS(comp,fullname)
```
