---
title: "Meth_SVM"
author: "Mukai Wang"
date: "July 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(e1071)
library(dplyr)
library(tictoc)
library(reshape2)
library(ggplot2)
```


```{r}
gdsc = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/gdsc_screened.rds')
meth = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/methylation_processed.rds')
```

```{r}
meth_nona = t(na.omit(t(meth)))
```

```{r}
get.t <- function(dat, labs){
    # split the data into effective and ineffective
    effect <- dat[labs]
    ineffect <- dat[!labs]
    
    # calculate the two sample means
    effect.bar <- mean(effect)
    ineffect.bar <- mean(ineffect)
    
    # calculate the two sample variances
    v.effect <- var(effect)
    v.ineffect <- var(ineffect)
    
    # calculate the sample sizes
    n.effect <- length(effect)
    n.ineffect <- length(ineffect)
    
    # calculate the sd
    s <- sqrt((v.effect/n.effect) + (v.ineffect/n.ineffect))
    
    # calculate the test statistic
    T.value <- (effect.bar - ineffect.bar)/s
    return(abs(T.value))
}
```

```{r}
codes <- c("1006","1007","1008","1011","1014","1016","1019","1026","1032","1054","1060","1062")
resultmat = matrix(nrow=12,ncol=6)
rownames(resultmat) = c("1006","1007","1008","1011","1014","1016","1019","1026","1032","1054","1060","1062")
colnames(resultmat) = c("2","3","5","10","20","50")
```

```{r}
directory = '/home/wangmk/UM/Research/BDSI/meth_sub'
```

```{r}
for (code in codes){
  filename = paste(c('meth',code,'subset','id.rds'),collapse='_')
  fullname = paste(c(directory,filename),collapse='/')
  sub = readRDS(fullname)
  print(code)
  gdsc_sub <- subset(gdsc, DRUG_ID_lib == code)[,c("CL","EFFECT")]
  meth_sub <- meth_nona[as.character(gdsc_sub$CL),sub]
  outcome <- data.frame(CG = colnames(meth_sub))
  meth_sub_full <- cbind(meth_sub, gdsc_sub['EFFECT'])
  # outcome$T <- apply(meth_sub,2,get.t,gdsc_sub$EFFECT)
  n_features = c(2,3,5,10,20,50)
  for (n_feature in n_features){
    print(n_feature)
    accuracy_test_svm = c()
    for (j in 1:3){  
      set.seed(j)
      train_id=sample(1:nrow(meth_sub_full),0.7*nrow(meth_sub_full))
      train_meth = meth_sub_full[train_id,]
      test_meth = meth_sub_full[-train_id,]
      outcome$T <- apply(train_meth[,-ncol(train_meth)], 2, get.t, train_meth$EFFECT)
      subset_id = outcome %>% top_n(n_feature,T) %>% select(CG)
      subset_id = unname(t(subset_id[,1]))
      train_meth_reduced = cbind(train_meth[,subset_id],train_meth['EFFECT'])
      test_meth_reduced = cbind(test_meth[,subset_id],test_meth['EFFECT'])
      train_meth_reduced$EFFECT <- as.factor(train_meth_reduced$EFFECT)
      test_meth_reduced$EFFECT <- as.factor(test_meth_reduced$EFFECT)
      tune.out = tune ( svm , EFFECT~., data = train_meth_reduced , 
                 ranges = list ( cost = c (0.01 , 0.1 , 1 ,10 ,100,1000),gamma=c(0.01,0.1,1,10,100,1000) ) )
      mysvm = svm(EFFECT~.,data=train_meth_reduced,kernel="radial",cost=tune.out$best.model$cost,gamma=tune.out$best.model$gamma,scale=FALSE)
            # training_pred = predict(mysvm,train_sub)
            # accuracy_train_svm[i] = mean(training_pred==train_sub[['EFFECT']])
      test_pred = predict(mysvm,test_meth_reduced)
      accuracy_test_svm[j] = mean(test_pred==test_meth_reduced[['EFFECT']])
  }
  resultmat[code,toString(n_feature)] = mean(accuracy_test_svm)
  }
}
```