---
title: "Meth_RF_Simple"
author: "Mukai Wang"
date: "July 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(randomForest)
library(dplyr)
library(ggplot2)
library(reshape2)
```

```{r}
gdsc = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/gdsc_screened.rds')
meth = readRDS('/home/wangmk/UM/Research/BDSI/Data_Results/methylation_processed.rds')
```


```{r}
traindirect = '/home/wangmk/UM/Research/BDSI/train_drug/'
```

```{r}
outdir = '/home/wangmk/UM/Research/BDSI/Data_Results/RF/'
```

```{r}
meth = t(na.omit(t(meth)))
```

```{r}
get.t <- function(dat, labs){
    # split the data into effective and ineffective
    effect <- dat[labs]
    ineffect <- dat[!labs]
    
    # calculate the two sample means
    effect.bar <- mean(effect)
    ineffect.bar <- mean(ineffect)
    
    # calculate the two sample variances
    v.effect <- var(effect)
    v.ineffect <- var(ineffect)
    
    # calculate the sample sizes
    n.effect <- length(effect)
    n.ineffect <- length(ineffect)
    
    # calculate the sd
    s <- sqrt((v.effect/n.effect) + (v.ineffect/n.ineffect))
    
    df = ((v.effect/n.effect+v.ineffect/n.ineffect)^2)/(v.effect^2/(n.effect^2 * (n.effect-1))+v.ineffect^2/(n.ineffect^2 * (n.ineffect-1)))
    # calculate the test statistic
    T.value <- (effect.bar - ineffect.bar)/s
    return(abs(T.value)>qt(1-0.005/475915,df))
}
```

```{r}
code = "1008"
gdsc_sub <- subset(gdsc, DRUG_ID_lib == code)[,c("CL","EFFECT")]
meth_sub <- meth[as.character(gdsc_sub$CL),]
#meth_sub_full <- cbind(meth_sub, gdsc_sub['EFFECT'])
#meth_sub <- NULL

filename = paste(c('train_',code,'.rds'),collapse='')
fullname = paste(c(traindirect,filename),collapse='')
cl_train = paste(readRDS(fullname))
cl_test = setdiff(rownames(meth_sub),cl_train)
gdsc_sub_train = tbl_df(gdsc_sub) %>% filter(CL %in% cl_train) %>% select(EFFECT)
meth_sub_train = meth_sub[cl_train,]
meth_sub_test = meth_sub[cl_test,]
outcome <- data.frame(CG = colnames(meth))
outcome$keep <- apply(meth_sub_train, 2, get.t, gdsc_sub_train$EFFECT)
```

```{r}
sum(outcome$keep==TRUE)
```